---
title: "Análise Education Statistics"
author: "Marcelle Chiriboga"
date: '2019-10-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(data.table)
```

## Load the Data

A base de dados refere-se ao percentual de repetentes na educação primária em diferentes países, disponibilizado por [The World Bank](https://databank.worldbank.org/indicator/SE.PRM.REPT.ZS?id=c755d342&report_name=EdStats_Indicators_Report&populartype=series#).

```{r Carrega dados, include = FALSE}
# Carrega os dados num data frame
education_stats <- read.csv("./EdStats_Indicators_Report/a40518c9-f54e-487f-a29f-5f6cd5982c20_Data.csv", na.strings = c('NA', '..'))
```

```{r Renomeia colunas}
# Renomeia colunas do data frame
setnames(education_stats,
         old = c("X2008..YR2008.", "X2009..YR2009.", "X2010..YR2010.", "X2011..YR2011.", "X2012..YR2012.", "X2013..YR2013.", "X2014..YR2014.", "X2015..YR2015.", "X2016..YR2016.", "X2017..YR2017.", "X2018..YR2018."), 
         new = c("2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018"))
```

```{r Reestrutura dados anuais}
# Transforma colunas de anos em observações
education_stats <- education_stats %>% 
  gather(Year, Indicator, `2008`:`2018`)
```

```{r Escreve .csv}
# Salva o data frame tratado em formato .csv
write.csv(education_stats, "../Analysis/education_stats.csv", row.names = FALSE)
```

